fix: show nice message on no distgit changes and unbreak gate
Ensure this behavior in fix feature test.

Manually, this scenario can be reproduced by;

    rdopkg fix; git stash; rdopkg --continue

Additionally, this patch contains small fixes to unbreak rdopkg CI gate after
not so smooth transition to tox.

Require pyOpenSSL >= 16.2.0 as pyOpenSSL==0.15.1 results in

    AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Fix python 3 compatibility for py3-feature tests.

Change-Id: I96925dd0565e088e067315ebc0e1533c0bb14ae8