fix: show nice message on no distgit changes
instead of git command failure.

Ensure this behavior in fix feature test.

Manually, this scenario can be reproduced by;

    rdopkg fix; git stash; rdopkg --continue

Also Require pyOpenSSL >= 16.2.0 to unbork rdopkg gate.

pyOpenSSL==0.15.1 results in

    AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Change-Id: I2f8913b933b97b0471a78453b15033df4c23858a