Fix git module import path
We forgot to update this during git module split resulting in:

AttributeError: 'module' object has no attribute 'git'

during `rdopkg info` and other actions.

Change-Id: Ie449e16f6768cfb6ccbd9d39ef4ce83d7a4712e9