Fix #180: pkgenv fails with TypeError
When we run rdopkg pkgenv we get:

  TypeError: sequence item 7: expected string or Unicode, int found

That happens because one of the params to the command is an integer,
which will fail on the join method call.

This patch ensure that all the params are strings.

Change-Id: Id37dc6d67c1e2b77551d598476af49355dc43891