exception: support exit_value
RdopkgException now contains exit_value which is returned by CLI on exit when
exception is raised.

Default exit_value can be set per exception and overriden when raising.

Change-Id: I85ff74d1a99095a7e8a41e33c146512562e7598c