exception: support exit_code
RdopkgException now contains exit_code which is returned by CLI on exit when
exception is raised.

Default exit_code can be set per exception and overriden when raising.

Change-Id: I85ff74d1a99095a7e8a41e33c146512562e7598c