Fix #179: Patch fails with int has no attr split
When we run rdopkg patch we get the following error:
  AttributeError: 'int' object has no attribute 'split'

This happens because the review number is precisely that, a number, but
the _review_number method expects it to be a string.

This patch adds support for numbers (non-strings) in the _review_number
method.

Change-Id: I79906c4b07e4073c165a0afcce638dd8daef00cf