Fix TypeError during new-sources on python3
map/filter now return iterables rather than lists. Some callers
of this function expect a list, so let's ensure we return that.

Fixes the following crash:

  File "rdopkg/actions/distgit/actions.py", line 743, in new_sources
    cmd = fedpkg + ['new-sources'] + sources
  TypeError: can only concatenate list (not "map") to list

Change-Id: If5f8dcb085bfd4ce13590ecfebafebee3b5c3d51