update-patches: Smarter .spec patch management
A newline after SourceX isn't required anymore.

Append PatchXXX after last SourceX tag.

Normalize spacing.

After this change, rdopkg should be able to manage any .spec file with SourceX
tag and %setup macro, hopefully getting rid of the infamous

    SpecFileParseError: Error parsing .spec file 'foo.spec': Failed to append PatchXXXX: lines

Includes new unit tests for dense .spec files.

Fixes #1
Fixes #15
Fixes #18