Bugfix: fix cbsbuild command failure
cbsbuild fails when watching koji tasks with the following message
> AttributeError: 'dict' object has no attribute 'poll_interval'

In a previous change, we use plain dict to pass Koji clients
options, but some other Koji methods expect an object.
Introduce Bunch library to solve that issue.

Change-Id: Id762c1fc1cde67075c4b975aa2d767ea6738743a