Use absolute path for repo_path
rdopkg is changing to a different directory that the one
from where the command was executed in some operations as
when doing rdopkg info. This means that when using relative
paths as in:

rdopkg info -l rdoinfo openstack-nova

it's failing with error:

ImportError: No module named rdoinfo

This patch converts repo_pat to absolute path so that it's
valid even when changing current directory.

Change-Id: I0f7624ffcee10a8abcfc5128ec1ed9dc2f69c35a